version: "3"
services:
  db:
    image: mysql:8.0.26
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    container_name: codehansabari-db
    environment:
      - MYSQL_ROOT_PASSWORD=team2
      - MYSQL_DATABASE=cvmentodb
      - TZ=Asia/Seoul
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 10
    ports:
      - "3312:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: codehansabari-redis
    command: redis-server --requirepass team2
    ports:
      - "6381:6379"
    restart: always